#!/bin/sh
#
# /etc/rc.d/net: start/stop network
#

case $1 in
start)
	/sbin/ifconfig lo 127.0.0.1
	#/sbin/ifconfig eth0 xxx.xxx.xxx.xxx netmask 255.255.255.xxx
	#/sbin/route add default gw xxx.xxx.xxx.xxx
	;;
stop)
	#/sbin/ifconfig eth0 down
	/sbin/ifconfig lo down
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
