#!/bin/sh
#
# /etc/rc.d/portmap: start/stop portmap daemon
#

case $1 in
start)
	/sbin/portmap -t /var/empty
	;;
stop)
	killall -q /sbin/portmap
	;;
restart)
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "usage: $0 [start|stop|restart]"
	;;
esac

# End of file
